from src.view.committee.add_member import *
from src.view.committee.committee_detail import *
from src.view.committee.committee_home import *
from src.view.committee.committee_index import *
from src.view.committee.create_vote import *
from src.view.committee.documents import *
from src.view.committee.manage_members import *
from src.view.committee.minutes import *
from src.view.committee.push_to_chapter import *
from src.view.committee.remove_member import *
from src.view.committee.upload_document import *
from src.view.committee.vote import *
from src.view.committee.toggle_document_publish import *
from src.view.committee.delete_document import *
