# Generated by Django 5.2.15 on 2026-07-08 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_seed_pledge_page_restrictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(blank=True, help_text='Leave blank to apply this item to every role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='src.role')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransitionChecklistStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.transitionchecklistitem')),
                ('role_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_statuses', to='src.rolehistory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'role_history'), name='uniq_item_per_rolehistory')],
            },
        ),
    ]
