# v3.13.2 — convert plurality_options from postgres ArrayField (varchar[])
# to the backend-agnostic JSONField, so sqlite dev/test DBs can migrate.
#
# Why hand-written instead of the autogenerated AlterField:
#   Postgres has no direct varchar[] -> jsonb cast, so Django's default
#   `USING plurality_options::jsonb` would fail on prod. We need
#   `USING to_jsonb(plurality_options)` (['a','b'] -> ["a","b"], NULL -> NULL).
#
# State-wise, 0001_initial was edited in the same change to declare these two
# fields as JSONField (it had never produced a working column on any
# non-postgres backend, and prod applied it via the 07-05 fake-initial
# cutover, so its recorded state is whatever the file says now). That means:
#   - fresh sqlite/CI-postgres DBs create jsonb/JSON columns directly in 0001
#     (the to_jsonb ALTER below is valid and a no-op on an already-jsonb column);
#   - prod, whose real column is still varchar[], gets converted here.
from django.db import migrations


def convert_pg_array_to_jsonb(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return  # sqlite creates JSONField directly from (edited) 0001
    for table in ('src_legislation', 'src_committeelegislation'):
        schema_editor.execute(
            f'ALTER TABLE {table} '
            f'ALTER COLUMN plurality_options TYPE jsonb '
            f'USING to_jsonb(plurality_options)'
        )


def convert_jsonb_back_to_pg_array(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    for table in ('src_legislation', 'src_committeelegislation'):
        schema_editor.execute(
            f'ALTER TABLE {table} '
            f'ALTER COLUMN plurality_options TYPE varchar(100)[] '
            f"USING (SELECT array_agg(x) FROM jsonb_array_elements_text(plurality_options) AS t(x))"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_transitionchecklistitem_transitioncheckliststatus'),
    ]

    operations = [
        migrations.RunPython(
            convert_pg_array_to_jsonb,
            convert_jsonb_back_to_pg_array,
        ),
    ]
