# Generated by Django 5.1 on 2026-07-15 (v3.13.3 — state-only: adds draft to STATUS_CHOICES after removing the duplicate status field definition; no database operation) 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_plurality_options_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (Open)'), ('pending', 'Pending'), ('active', 'Active Voting'), ('passed', 'Passed'), ('failed', 'Failed'), ('tabled', 'Tabled'), ('removed', 'Removed')], default='draft', max_length=20),
        ),
    ]
