# Generated by Django 5.2.15 on 2026-07-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_legislation_status_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='voting_manual_open',
            field=models.BooleanField(default=False, help_text='Voting stays closed until the author opens it manually (only meaningful while voting_starts_at is empty)'),
        ),
    ]
