# Generated by Django 5.2.15 on 2026-07-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_legislation_voting_manual_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='cast_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
