# Generated by Django 5.2.16 — v3.16.3, 07-28-26
#
# NO-OP AT THE DATABASE LEVEL. `help_text` is part of a field's deconstruction,
# so changing it makes Django want a migration, but it emits no SQL — the column
# is untouched. This exists only to keep `makemigrations --check` clean.
#
# The text itself is the point: `KaiReportTemplate.suggested_tags` feeds straight
# into `KaiReport.tags`, which became a closed vocabulary in v3.16.3 because free
# text there leaked member identities to every reviewer holding only
# `can_view_report_list` (tags are searched ungated by `_kai_search_q`, rendered
# on the list card, and written to the CSV export). Anyone reading the field in
# the admin should see why it is restricted before they try to widen it.
#
# The vocabulary itself is `KaiReport.TAG_CHOICES` — a Python-level constant on a
# JSONField, deliberately not a DB constraint and not `choices=` on the field, so
# adding a tag later needs no schema change and no migration. Enforcement lives in
# `KaiReport.normalize_tags()` at every write site, plus `clean()` on both models.
#
# Existing rows are cleaned by `manage.py normalize_kai_tags`, which is a separate
# deploy step and deliberately NOT part of this migration: it edits disciplinary
# records, so it defaults to a dry run and wants a human to read the output before
# anything is dropped. Running `migrate` alone does not close the leak in existing
# data.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_vote_cast_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaireporttemplate',
            name='suggested_tags',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    'Tags pre-selected for reports created from this template. Restricted to '
                    'KaiReport.TAG_CHOICES — this feeds straight into KaiReport.tags, so a '
                    'free-text value here would reopen the identity leak that vocabulary closes.'
                ),
            ),
        ),
    ]
