# Generated by Django 5.2.16 on 2026-07-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_alter_kaireporttemplate_suggested_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='object_id',
            field=models.CharField(blank=True, help_text='ID of the affected object (string — user pks are not integers)', max_length=64, null=True),
        ),
    ]
