# Generated by Django 5.2.16 on 2026-07-31 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_case_numbers(apps, schema_editor):
    """
    Assign KAI-<year>-NNN to every existing case.

    v3.18.0. Numbered in submission order within each year, so the numbers
    read chronologically the way a case log should. `KaiReport.save()` handles
    new rows; this is only for rows that predate the field.

    Uses the historical model, so `KaiReport.save()` and its auto-assignment
    are deliberately NOT available here — the numbering is done explicitly.
    """
    KaiReport = apps.get_model('src', 'KaiReport')
    counters = {}
    for report in KaiReport.objects.order_by('submitted_at', 'pk').iterator():
        if report.case_number:
            continue
        year = report.submitted_at.year if report.submitted_at else 0
        counters[year] = counters.get(year, 0) + 1
        report.case_number = f'KAI-{year}-{counters[year]:03d}'
        report.save(update_fields=['case_number'])


def unbackfill_case_numbers(apps, schema_editor):
    """Reverse: clear them. The field is dropped by the schema operation anyway."""
    KaiReport = apps.get_model('src', 'KaiReport')
    KaiReport.objects.update(case_number='')


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_attendance_date_localdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaireport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Committee member handling this case. Independent of reviewed_by.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kai_reports_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kaireport',
            name='case_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Per-year case identifier, e.g. KAI-2026-014. Assigned automatically.', max_length=20),
        ),
        migrations.AlterField(
            model_name='kaireportactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Report Created'), ('status_changed', 'Status Changed'), ('deliberation_updated', 'Deliberation Outcome Updated'), ('notes_updated', 'Chair Notes Updated'), ('tags_updated', 'Tags Updated'), ('committee_notes_updated', 'Committee Notes Updated'), ('minutes_closed', 'Minutes Closed'), ('archived', 'Report Archived'), ('closure_requested', 'Closure Requested'), ('closure_approved', 'Closure Request Approved'), ('closure_denied', 'Closure Request Denied'), ('standin_appointed', 'Stand-In Appointed'), ('standin_removed', 'Stand-In Withdrawn'), ('appeal_filed', 'Appeal Filed'), ('appeal_decided', 'Appeal Decided')], max_length=30),
        ),
        migrations.CreateModel(
            name='KaiAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('chapter', 'The Chapter'), ('district_chief', 'District Chief'), ('board', 'Board of Trustees'), ('convention', 'General Convention')], default='chapter', max_length=20)),
                ('grounds', models.TextField(help_text='The basis on which the decision is being appealed.')),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('under_review', 'Under Review'), ('upheld', 'Decision Upheld'), ('overturned', 'Decision Overturned'), ('modified', 'Decision Modified'), ('withdrawn', 'Withdrawn')], default='filed', max_length=20)),
                ('outcome_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kai_appeals_decided', to=settings.AUTH_USER_MODEL)),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kai_appeals_filed', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='src.kaireport')),
            ],
            options={
                'verbose_name': 'Kai Appeal',
                'verbose_name_plural': 'Kai Appeals',
                'ordering': ['-filed_at'],
            },
        ),
        migrations.CreateModel(
            name='KaiRecusal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('accused', 'Named in the case'), ('submitter', 'Submitted the case'), ('conflict', 'Declared conflict of interest'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional context. Visible to the committee, not to the parties.')),
                ('granted_permissions', models.JSONField(blank=True, default=dict, help_text="Snapshot of the replaced seat's permissions, taken at appointment.")),
                ('appointed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kai_recusals_recorded', to=settings.AUTH_USER_MODEL)),
                ('replacement', models.ForeignKey(blank=True, help_text='Member appointed to fill the recused seat for this case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kai_recusal_replacements', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recusals', to='src.kaireport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kai_recusals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kai Recusal',
                'verbose_name_plural': 'Kai Recusals',
                'ordering': ['-created_at'],
                'unique_together': {('report', 'user')},
            },
        ),
        migrations.RunPython(backfill_case_numbers, unbackfill_case_numbers),
    ]
