# Generated by Django 5.2.16 on 2026-08-01
#
# v3.18.1. Two operations, one of which exists only to keep a gate green.
#
# 1. `AlterField` on `kairecusal.reason` — choices only, NO DDL. `unavailable`
#    was added to `KaiRecusal.REASON_CHOICES` after 0011 was generated, so
#    `makemigrations --check --dry-run` exited 1 and CI
#    (`.github/workflows/ci.yml:74`) had been red since `eb9f72e`. Nothing was
#    broken at runtime — `choices` is validation metadata and
#    `get_reason_display()` reads the model, not the migration — but a gate
#    that is red for an unrelated reason is a gate nobody reads, and this
#    codebase has already shipped past one guard that way (v3.17.7). Same
#    reasoning as `0008_alter_kaireporttemplate_suggested_tags`.
#
# 2. `AddConstraint` on `kaireport.case_number` — a partial unique index.
#    `KaiReport.next_case_number()` reads the highest number for the year and
#    adds one, so two submissions landing together can both read the same
#    maximum. Case numbers go into chapter minutes; two cases sharing one is
#    worse than a gap. `KaiReport.save()` catches the IntegrityError and
#    recomputes once. Partial (`WHERE case_number <> ''`) because the field
#    defaults to blank and `bulk_create`d fixtures legitimately leave many.
#
# `_dedupe_case_numbers` runs first so the constraint cannot fail to apply on a
# database that somehow already holds a collision. It is expected to be a no-op
# — 0011's backfill numbered per year in submission order and could not produce
# one — but an AddConstraint that aborts a production `migrate` halfway is a
# bad way to discover otherwise.

from django.db import migrations, models


def _dedupe_case_numbers(apps, schema_editor):
    """Renumber any duplicate case numbers before the unique index goes on."""
    KaiReport = apps.get_model('src', 'KaiReport')
    seen = set()
    for report in KaiReport.objects.exclude(case_number='').order_by('pk').iterator():
        if report.case_number not in seen:
            seen.add(report.case_number)
            continue
        # Collision. Walk to the next free number in the same year.
        prefix = report.case_number.rsplit('-', 1)[0] + '-'
        tail = report.case_number.rsplit('-', 1)[-1]
        counter = int(tail) if tail.isdigit() else 0
        while True:
            counter += 1
            candidate = f'{prefix}{counter:03d}'
            if candidate not in seen and not KaiReport.objects.filter(
                case_number=candidate,
            ).exclude(pk=report.pk).exists():
                break
        report.case_number = candidate
        report.save(update_fields=['case_number'])
        seen.add(candidate)


def _noop(apps, schema_editor):
    """Reversing the constraint needs no data change."""


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_kai_recusal_appeals_case_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kairecusal',
            name='reason',
            field=models.CharField(choices=[('accused', 'Named in the case'), ('submitter', 'Submitted the case'), ('unavailable', 'Unavailable for this case'), ('conflict', 'Declared conflict of interest'), ('other', 'Other')], max_length=20),
        ),
        migrations.RunPython(_dedupe_case_numbers, _noop),
        migrations.AddConstraint(
            model_name='kaireport',
            constraint=models.UniqueConstraint(condition=models.Q(('case_number', ''), _negated=True), fields=('case_number',), name='uniq_kai_report_case_number'),
        ),
    ]
