# Generated by Django 5.2.17 on 2026-08-19 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_confidential_upload_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgetask',
            name='max_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional. If set, this task is SCORED out of this many points and a chair records what each pledge earned (e.g. 50/60). Leave blank for pass/fail. Separate from "points", which is progress/gamification and is the same for everyone who completes the task.', null=True),
        ),
        migrations.AddField(
            model_name='pledgetaskcompletion',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Points this pledge earned, out of the task's max_score (e.g. 50 of 60). Only meaningful when the task has a max_score.", null=True),
        ),
        migrations.AlterField(
            model_name='pledgetaskcompletion',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes from the reviewer (e.g. what was missed, observations). v3.20.0: scores now have their own field — use `score`, not this.'),
        ),
        migrations.CreateModel(
            name='EducationMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('meeting', 'Pledge Meeting'), ('study', 'Study Session'), ('ritual', 'Ritual Practice'), ('test', 'Test / Exam'), ('service', 'Service Event'), ('other', 'Other')], default='meeting', max_length=20)),
                ('attendance_required', models.BooleanField(default=True, help_text='Whether pledges are expected at this meeting. Attendance can be taken either way; this drives what the pledge is told.')),
                ('points', models.PositiveSmallIntegerField(default=0, help_text='Points a pledge earns for attending. Awarded for "present" only — excused costs nothing but earns nothing.')),
                ('notes', models.TextField(blank=True, help_text='Chair-facing notes. Not shown to pledges.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_meetings', to='src.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_education_meetings', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_meeting', to='src.event')),
                ('homework', models.ManyToManyField(blank=True, help_text='Tasks assigned as homework at this meeting.', related_name='education_meetings', to='src.pledgetask')),
            ],
            options={
                'verbose_name': 'Education Meeting',
                'verbose_name_plural': 'Education Meetings',
                'ordering': ['-event__date_time'],
            },
        ),
        migrations.CreateModel(
            name='EducationMeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Not marked'), ('present', 'Present'), ('excused', 'Excused'), ('late', 'Late'), ('absent', 'Absent')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_education_attendance', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='src.educationmeeting')),
                ('pledge', models.ForeignKey(limit_choices_to={'member_type': 'Pledge'}, on_delete=django.db.models.deletion.CASCADE, related_name='education_meeting_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education Meeting Attendance',
                'verbose_name_plural': 'Education Meeting Attendance',
                'ordering': ['meeting', 'pledge__name'],
                'indexes': [models.Index(fields=['meeting', 'status'], name='src_educati_meeting_d616de_idx'), models.Index(fields=['pledge', 'status'], name='src_educati_pledge__dc87f4_idx')],
                'unique_together': {('meeting', 'pledge')},
            },
        ),
    ]
