# Generated by Django 5.2.17 on 2026-08-20 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_education_scoring_and_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgequizanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pledgetask',
            name='show_analysis_to_pledges',
            field=models.BooleanField(default=False, help_text='Off by default: the question-by-question breakdown is for educators. Turn on to let pledges see it for this quiz too — useful after a review session, when knowing which questions the class missed is the point rather than who missed them.'),
        ),
        migrations.CreateModel(
            name='EducationAbsenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Why the pledge cannot attend.')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, help_text='Optional note back to the pledge.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_requests', to='src.educationmeeting')),
                ('pledge', models.ForeignKey(limit_choices_to={'member_type': 'Pledge'}, on_delete=django.db.models.deletion.CASCADE, related_name='education_absence_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_education_absences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education Absence Request',
                'verbose_name_plural': 'Education Absence Requests',
                'ordering': ['-created_at'],
                'unique_together': {('meeting', 'pledge')},
            },
        ),
    ]
