# Generated by Django 5.2.17 on 2026-08-27 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0022_user_id_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCheckinWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=43, unique=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('closed_early_at', models.DateTimeField(blank=True, null=True)),
                ('closed_early_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_checkin_windows', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_windows', to='src.event')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_checkin_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Check-in Window',
                'verbose_name_plural': 'Event Check-in Windows',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['event', 'expires_at'], name='src_eventch_event_i_14e6fd_idx')],
            },
        ),
    ]
