# Generated by Django 5.2.17 on 2026-08-27 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0023_event_checkin_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCheckinEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=43, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checkin_embeds', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_embed', to='src.event')),
            ],
            options={
                'verbose_name': 'Event Check-in Embed Link',
                'verbose_name_plural': 'Event Check-in Embed Links',
            },
        ),
    ]
