# Generated by Django 5.2.17 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0024_event_checkin_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_1_email_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Also send an email reminder (in addition to the push notification) for the first reminder',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_2_email_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Also send an email reminder (in addition to the push notification) for the second reminder',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='reminder_1_sent_at',
            field=models.DateTimeField(
                blank=True, null=True,
                help_text='When the first reminder was dispatched (null = not yet sent)',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='reminder_2_sent_at',
            field=models.DateTimeField(
                blank=True, null=True,
                help_text='When the second reminder was dispatched (null = not yet sent)',
            ),
        ),
        migrations.AddField(
            model_name='eventreminderlog',
            name='users_with_email',
            field=models.IntegerField(default=0, help_text='Eligible users with an email address on file'),
        ),
        migrations.AddField(
            model_name='eventreminderlog',
            name='users_email_opted_out',
            field=models.IntegerField(default=0, help_text='Users with email who opted out of email_events'),
        ),
        migrations.AddField(
            model_name='eventreminderlog',
            name='emails_dispatched',
            field=models.IntegerField(default=0, help_text='Number of reminder emails successfully sent'),
        ),
        migrations.AddField(
            model_name='eventreminderrecipient',
            name='email_status',
            field=models.CharField(
                blank=True, default='', max_length=30,
                choices=[
                    ('dispatched', 'Dispatched'),
                    ('skipped_opted_out', 'Skipped — Opted Out'),
                    ('skipped_no_email', 'Skipped — No Email Address'),
                    ('failed', 'Failed to Send'),
                ],
                help_text="Blank when this reminder slot's email option was off",
            ),
        ),
    ]
