# Generated by Django 5.2.17 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0025_event_reminder_email_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreminderrecipient',
            name='viewed_at',
            field=models.DateTimeField(
                blank=True, null=True,
                help_text='When this recipient opened the reminder email (tracking pixel hit) — null if never opened (or no email was sent to them)',
            ),
        ),
    ]
