# Generated by Django 5.2.17 on 2026-09-02 17:09
#
# v3.28.6 — backfill for the announcement view-stat fix (see
# src/models/announcements.py::Announcement.target_audience_snapshot for the
# full reasoning). This data migration is best-effort and says so:
#
# It snapshots every already-published Announcement against the CURRENT
# roster, because that's the only roster this migration can see — there is
# no historical record of who held which member_type on the date each
# announcement was actually posted. For most announcements that's a fine
# approximation (membership doesn't churn every day). For the one that
# motivated this fix — an announcement targeted at a pledge class that has
# since fully initiated — the true original audience is genuinely
# unrecoverable, and this backfill will (correctly, if unhelpfully) compute
# zero. What it fixes for that case is the impossible-looking display (view
# counts exceeding a stale denominator); it cannot restore lost history.
# Going forward, every newly-published announcement gets an accurate
# snapshot taken close to its real publish moment instead.

from django.db import migrations, models


def backfill_target_audience(apps, schema_editor):
    Announcement = apps.get_model('src', 'Announcement')
    ParliamentUser = apps.get_model('src', 'ParliamentUser')
    UserAnnouncementView = apps.get_model('src', 'UserAnnouncementView')

    active_by_type = {}
    for row in (
        ParliamentUser.objects.filter(member_status='Active')
        .values('member_type', 'user_id')
    ):
        active_by_type.setdefault(row['member_type'], []).append(row['user_id'])

    for announcement in Announcement.objects.filter(is_active=True):
        # Mirror Announcement.is_published() / target_member_types(), which
        # aren't available on the historical model this migration sees.
        if announcement.publish_at is not None:
            from django.utils import timezone
            if timezone.now() < announcement.publish_at:
                continue

        visible_to = announcement.visible_to
        if not visible_to:
            snapshot = [uid for ids in active_by_type.values() for uid in ids]
        else:
            types = set(visible_to)
            if 'Member' in types:
                types |= {'Chair', 'Officer'}
            snapshot = [uid for t in types for uid in active_by_type.get(t, [])]

        announcement.target_audience_snapshot = sorted(set(snapshot))
        announcement.save(update_fields=['target_audience_snapshot'])

    # Now that every published announcement has a snapshot, tell each
    # existing view row whether its viewer was in it.
    for view in UserAnnouncementView.objects.select_related('announcement').all():
        counted = view.user_id in (view.announcement.target_audience_snapshot or [])
        if view.counted_in_target != counted:
            view.counted_in_target = counted
            view.save(update_fields=['counted_in_target'])


def noop_reverse(apps, schema_editor):
    # Deliberate no-op. Reversing this migration removes the columns (below);
    # there's nothing meaningful to "undo" about the backfilled values
    # themselves, and re-deriving what they were before would just be running
    # this same best-effort computation again.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0026_event_reminder_email_view_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_audience_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='User IDs of members eligible to view this announcement, frozen the first time it is viewed or its stats are checked after publishing. Denominator for view-rate stats — see ensure_target_audience_snapshot().'),
        ),
        migrations.AddField(
            model_name='userannouncementview',
            name='counted_in_target',
            field=models.BooleanField(default=True, help_text="Whether this view counts toward the announcement's view-rate stats — false for a member who could technically open the page (e.g. an alumnus who still has an account, or a wrong-member-type viewer) but wasn't part of who the announcement was actually published to."),
        ),
        migrations.RunPython(backfill_target_audience, noop_reverse),
    ]
