# Generated by Django 5.2.17 on 2026-09-02 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0027_announcement_view_target_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementPollEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=43, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_poll_qr_embeds', to=settings.AUTH_USER_MODEL)),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_embed', to='src.announcementpoll')),
            ],
            options={
                'verbose_name': 'Poll QR Embed Link',
                'verbose_name_plural': 'Poll QR Embed Links',
            },
        ),
    ]
