# Generated by Django 5.2.17 on 2026-09-02 17:25

import django.db.models.deletion
import src.models.kai_accommodations
import src.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0028_poll_qr_embed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kaiformfield',
            options={'ordering': ['form_type', 'section', 'display_order'], 'verbose_name': 'Kai Form Field', 'verbose_name_plural': 'Kai Form Fields'},
        ),
        migrations.AddField(
            model_name='kaiformfield',
            name='form_type',
            field=models.CharField(choices=[('discipline', 'Discipline Report'), ('accommodation', 'Accommodation Request')], db_index=True, default='discipline', help_text='Which Kai form this field appears on.', max_length=20),
        ),
        migrations.CreateModel(
            name='KaiAccommodationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief summary of what the accommodation is for', max_length=255)),
                ('description', models.TextField(help_text='Details of the accommodation being requested')),
                ('attachment', models.FileField(blank=True, help_text="Optional supporting document (e.g. a doctor's note)", null=True, storage=src.storage.DualLocationStorage(), upload_to=src.models.kai_accommodations.kai_accommodation_attachment_path)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_review', 'Under Review'), ('approved', 'Approved'), ('denied', 'Denied'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('committee_notes', models.TextField(blank=True, help_text='Internal committee notes — not shown to the requester.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('request_number', models.CharField(blank=True, db_index=True, default='', help_text='Per-year request identifier, e.g. ACC-2026-014. Assigned automatically.', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Committee member handling this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kai_accommodation_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kai_accommodation_requests_submitted', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kai_accommodation_requests_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kai Accommodation Request',
                'verbose_name_plural': 'Kai Accommodation Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='KaiAccommodationFieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('json_value', models.JSONField(blank=True, null=True)),
                ('file_value', models.FileField(blank=True, null=True, storage=src.storage.DualLocationStorage(), upload_to=src.models.kai_accommodations.kai_accommodation_response_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_responses', to='src.kaiformfield')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_responses', to='src.kaiaccommodationrequest')),
            ],
            options={
                'verbose_name': 'Kai Accommodation Field Response',
                'verbose_name_plural': 'Kai Accommodation Field Responses',
            },
        ),
        migrations.CreateModel(
            name='KaiAccommodationRequestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Request Created'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('notes_updated', 'Committee Notes Updated'), ('resolved', 'Request Resolved')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='src.kaiaccommodationrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kai Accommodation Request Activity',
                'verbose_name_plural': 'Kai Accommodation Request Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='kaiaccommodationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('request_number', ''), _negated=True), fields=('request_number',), name='uniq_kai_accommodation_request_number'),
        ),
        migrations.AlterUniqueTogether(
            name='kaiaccommodationfieldresponse',
            unique_together={('request', 'field')},
        ),
    ]
