# Generated by Django 5.2.17 on 2026-09-03 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0030_rename_kai_accommodation_to_commendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='committee',
            field=models.ForeignKey(blank=True, help_text='If set, this is a committee meeting: attendance tracking, the excuse system, and push/email reminders are scoped to this committee\'s members and chairs — plus anyone who signs up, even if they aren\'t on the committee — instead of the whole chapter. Calendar visibility is still controlled separately by "Visible To" above.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_events', to='src.committee'),
        ),
    ]
