# Generated by Django 5.2.17 on 2026-09-03 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0031_event_committee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('feature_idea', 'Feature Idea'), ('support_ticket', 'Support Ticket / Contact')], default='support_ticket', help_text='Feature idea (public board) or a private support ticket to the admin?', max_length=20)),
                ('title', models.CharField(help_text='A short summary', max_length=200)),
                ('description', models.TextField(help_text='Describe the idea, or what you need help with, in detail')),
                ('page', models.CharField(blank=True, choices=[('home', 'Home Page'), ('login', 'Login Page'), ('profile', 'Profile Page'), ('preferences', 'Preferences'), ('legislation', 'Legislation'), ('voting', 'Voting'), ('committees', 'Committees'), ('documents', 'Documents'), ('announcements', 'Announcements'), ('events', 'Events'), ('attendance', 'Attendance'), ('officer_home', 'Officer Dashboard'), ('admin', 'Admin Panel'), ('roberts_rules', "Robert's Rules"), ('constitution', 'Constitution & Bylaws'), ('other', 'Other Page')], help_text='Which page or area is this about?', max_length=50)),
                ('page_url', models.CharField(blank=True, help_text='The URL this relates to (optional)', max_length=500)),
                ('feature', models.CharField(blank=True, help_text='Which specific feature or section? (e.g., "Vote button", "Document upload")', max_length=200)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low - Nice to have / no rush'), ('medium', 'Medium'), ('high', 'High - Would really help / fairly urgent'), ('urgent', 'Urgent')], default='medium', help_text='How much would this help you, or how urgent is it?', max_length=20)),
                ('attachment', models.FileField(blank=True, help_text='Screenshot or supporting file (optional)', null=True, upload_to='feedback_requests/%Y/%m/')),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('wont_fix', "Won't Do"), ('duplicate', 'Duplicate')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for administrators')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When this was resolved/closed', null=True)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved/closed this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_feedback_requests', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='User who submitted this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback / Support Request',
                'verbose_name_plural': 'Feedback / Support Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
