# Generated by Django 5.2.17 on 2026-09-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0032_feedbackrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehourssubmission',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Shared by every row created from the same multi-date submission form; null for a single-date submission.', null=True),
        ),
    ]
