# Generated by Django 5.2.17 on 2026-09-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0033_service_hours_batch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The quote itself.')),
                ('context', models.CharField(blank=True, help_text='Optional — where/when/why this was said, if it helps the joke land.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(blank=True, help_text='Who flagged this quote — the quoted member themselves, or an officer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_flagged', to=settings.AUTH_USER_MODEL)),
                ('quoted_member', models.ForeignKey(help_text='The member this quote is attributed to — whose chapter it appears on.', on_delete=django.db.models.deletion.CASCADE, related_name='quotes_about_them', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['quoted_member', 'flagged_at'], name='src_quote_quoted__58c9ef_idx')],
            },
        ),
    ]
