# Generated by Django 5.2.17 on 2026-09-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0034_quote_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Failed Login Attempt'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('legislation_created', 'Legislation Created'), ('legislation_edited', 'Legislation Edited'), ('legislation_deleted', 'Legislation Deleted'), ('legislation_reopened', 'Legislation Reopened'), ('vote_ended', 'Vote Ended'), ('vote_cast', 'Vote Cast'), ('vote_changed', 'Vote Changed'), ('committee_member_added', 'Committee Member Added'), ('committee_member_removed', 'Committee Member Removed'), ('committee_vote_created', 'Committee Vote Created'), ('committee_document_uploaded', 'Committee Document Uploaded'), ('committee_document_deleted', 'Committee Document Deleted'), ('committee_document_published', 'Committee Document Published to Chapter'), ('document_uploaded', 'Document Uploaded'), ('document_downloaded', 'Document Downloaded'), ('document_deleted', 'Document Deleted'), ('document_viewed', 'Document Viewed'), ('announcement_created', 'Announcement Created'), ('announcement_edited', 'Announcement Edited'), ('announcement_deleted', 'Announcement Deleted'), ('announcement_toggled', 'Announcement Status Toggled'), ('event_created', 'Event Created'), ('event_edited', 'Event Edited'), ('event_deleted', 'Event Deleted'), ('attendance_taken', 'Attendance Taken'), ('user_created', 'User Created'), ('user_edited', 'User Profile Edited'), ('user_role_changed', 'User Role Changed'), ('login_as_user', 'Admin Logged In As User'), ('profile_updated', 'Profile Updated'), ('profile_picture_changed', 'Profile Picture Changed'), ('preferences_updated', 'Preferences Updated'), ('settings_changed', 'System Settings Changed'), ('kai_action', 'Kai Report Action'), ('pledge_login', 'Pledge Login'), ('pledge_password_changed', 'Pledge Password Changed'), ('other', 'Other Action'), ('bug_report_submitted', 'Bug Report Submitted'), ('email_sent', 'Email Sent'), ('quote_submitted', 'Quote Added'), ('quote_flagged', 'Quote Flagged/Removed')], max_length=50),
        ),
    ]
