# Generated by Django 5.1.7 on 2025-12-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0034_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='requires_attendance',
            field=models.BooleanField(default=True, help_text='Check if this event requires attendance tracking (chapter meetings, etc.)'),
        ),
    ]
