# Generated by Django 5.1.7 on 2025-12-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0035_alter_event_requires_attendance'),
    ]

    operations = [
        # Increase username field length to accommodate encrypted data (Fernet tokens are ~200 chars)
        migrations.RunSQL(
            sql="ALTER TABLE src_parliamentuser ALTER COLUMN username TYPE VARCHAR(500);",
            reverse_sql="ALTER TABLE src_parliamentuser ALTER COLUMN username TYPE VARCHAR(100);"
        ),
        # Increase email field length to accommodate encrypted data
        migrations.RunSQL(
            sql="ALTER TABLE src_parliamentuser ALTER COLUMN email TYPE VARCHAR(500);",
            reverse_sql="ALTER TABLE src_parliamentuser ALTER COLUMN email TYPE VARCHAR(254);"
        ),
        # Increase IP address field length in login history
        migrations.RunSQL(
            sql="ALTER TABLE src_loginhistory ALTER COLUMN ip_address TYPE VARCHAR(500);",
            reverse_sql="ALTER TABLE src_loginhistory ALTER COLUMN ip_address TYPE VARCHAR(45);"
        ),
    ]
