# Generated by Django 5.2.17 on 2026-09-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0037_alter_activitylog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginalert',
            name='alert_type',
            field=models.CharField(choices=[('impossible_travel', 'Impossible Travel'), ('new_location', 'New Location'), ('new_device', 'New Device'), ('multiple_failures', 'Multiple Failed Attempts'), ('unusual_time', 'Unusual Login Time'), ('vpn_detected', 'VPN/Proxy Detected'), ('watch_flag', 'Watch Flag Alert'), ('weak_password', 'Weak/Compromised Password'), ('other', 'Other Suspicious Activity')], max_length=30),
        ),
    ]
