# Generated by Django 5.1.7 on 2025-12-29 21:56

import src.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0037_alter_loginhistory_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=src.encrypted_fields.EncryptedCharField(help_text='Encrypted IP address of login attempt', max_length=180),
        ),
        migrations.AlterField(
            model_name='parliamentuser',
            name='email',
            field=src.encrypted_fields.EncryptedEmailField(blank=True, help_text='Encrypted email address for password reset and notifications', max_length=1016, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parliamentuser',
            name='username',
            field=models.CharField(help_text='Username for login (not encrypted - needed for authentication lookups)', max_length=100, unique=True),
        ),
    ]
