# Generated by Django 5.2.17 on 2026-09-15 21:24
"""
v3.31.2 — backfill device_type/browser/operating_system for existing
BugReport rows.

The three fields this migration adds are populated going forward by
submit_bug_report() parsing the request's User-Agent header at submission
time (via UserSession.parse_user_agent(), the same parser the "Active
Sessions" feature already uses). That leaves every BugReport row filed
before this release with the three new columns blank — not because the
information was lost, just because it was never parsed out of the one
place it WAS already being stored: the existing `browser_info` field,
populated client-side (navigator.userAgent) since long before this change
and never re-derived.

Backfilling rather than leaving those rows blank follows this codebase's
own convention (see 0021_backfill_role_numbers) — new columns get filled
for historical rows when the source data to do it already exists.

Safe and bounded:
* Only touches rows where all three new fields are still blank, so a
  second run (or a partial run interrupted mid-way) is a no-op on
  anything already filled.
* Only reads `browser_info` — no new I/O, no network, no re-request of
  anything.
* `UserSession.parse_user_agent()` cannot raise on arbitrary input — it's
  substring/lowercase matching with safe fallthrough defaults
  ('desktop'/'Unknown'/'Unknown') — so there's no row this can fail on.
* Reverse is a no-op on purpose, same reasoning as 0021: un-parsing three
  derived fields back to blank isn't a rollback, it's just deleting
  information that was always recoverable from `browser_info` anyway, so
  there's nothing to protect by reversing.
"""
from django.db import migrations, models


def backfill_device_info(apps, schema_editor):
    BugReport = apps.get_model('src', 'BugReport')

    # The parser lives on UserSession as a classmethod with no ORM/instance
    # dependency (it's a pure string-in, tuple-out function) — safe to import
    # directly rather than duplicating the parsing logic here, and it can't
    # go stale relative to what new submissions use because it's the exact
    # same function.
    from src.models.users import UserSession

    candidates = BugReport.objects.filter(
        device_type='', browser='', operating_system='',
    ).exclude(browser_info='')

    updated = 0
    for report in candidates.iterator():
        device_type, browser, operating_system = UserSession.parse_user_agent(
            report.browser_info
        )
        report.device_type = device_type
        report.browser = browser
        report.operating_system = operating_system
        report.save(update_fields=['device_type', 'browser', 'operating_system'])
        updated += 1

    if updated:
        # Printed rather than logged, matching 0021 — migrations run on a
        # terminal someone is watching during a deploy.
        print(f'\n  0039: backfilled device/browser/OS on {updated} existing bug report(s).')


def noop_reverse(apps, schema_editor):
    """Deliberately does nothing. See the module docstring."""


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0038_alter_loginalert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='browser',
            field=models.CharField(blank=True, help_text="Browser name — parsed from the browser's user agent", max_length=100),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='device_type',
            field=models.CharField(blank=True, help_text="mobile / tablet / desktop — parsed from the browser's user agent", max_length=50),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='operating_system',
            field=models.CharField(blank=True, help_text="Operating system — parsed from the browser's user agent", max_length=100),
        ),
        migrations.RunPython(backfill_device_info, noop_reverse),
    ]
