# Generated by Django 5.2.17 on 2026-09-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0039_bugreport_browser_bugreport_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementpollresponse',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Set when the respondent changes their answer after initially submitting. Null if never edited.', null=True),
        ),
    ]
