# Generated by Django 5.2.17 on 2026-09-16 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0040_announcementpollresponse_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationMemberPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_submissions', models.BooleanField(default=False, help_text='Can view the dashboard, pledge progress, and quiz answers/submissions')),
                ('can_grade_submissions', models.BooleanField(default=False, help_text='Can mark quiz answers, enter scores, and set completion status (pass/incomplete)')),
                ('can_manage_tasks', models.BooleanField(default=False, help_text='Can create/edit/delete tasks and quiz questions, manage meetings and attendance, review absence requests, and edit pledge page restrictions')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(limit_choices_to={'is_education_committee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='education_member_permissions', to='src.committee')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education Member Permission',
                'verbose_name_plural': 'Education Member Permissions',
                'unique_together': {('committee', 'user')},
            },
        ),
    ]
