# Generated by Django 5.2.17 on 2026-09-16 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0041_education_member_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='src.role')),
            ],
        ),
        migrations.CreateModel(
            name='RoleKnowledgeBaseRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='src.roleknowledgebase')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
