# Generated by Django 5.2.17 on 2026-09-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0042_role_knowledge_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('legislation_new', 'New Legislation'), ('vote_ended', 'Vote Ended'), ('event_new', 'New Event'), ('chat_mention', 'Chat Mention'), ('security', 'Security Alert'), ('excuse_reviewed', 'Excuse Reviewed')], max_length=20),
        ),
    ]
