# Generated by Django 5.2.17 on 2026-09-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0044_role_kb_available_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pledgequizanswer',
            options={'base_manager_name': 'objects', 'ordering': ['question__display_order'], 'verbose_name': 'Pledge Quiz Answer', 'verbose_name_plural': 'Pledge Quiz Answers'},
        ),
    ]
