# Generated by Django 5.2.17 on 2026-09-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0045_alter_pledgequizanswer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentuser',
            name='is_anonymized',
            field=models.BooleanField(default=False, help_text="Set by anonymize() (09-18-26) — this row's identity/contact fields have been scrubbed and replaced with a 'Deleted User' placeholder. The row itself is kept (never hard-deleted) so votes, ballots, slating records, minutes, and everything else with a foreign key to this member survive. Distinct from member_status='Removed', which anonymize() also sets but which can be set on its own without scrubbing anything — this flag is the one that means 'and their PII is gone too.'"),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(choices=[('token_approved', 'API Token Approved'), ('token_denied', 'API Token Denied'), ('token_revoked', 'API Token Revoked'), ('token_scopes_edited', 'API Token Scopes Edited'), ('account_unlocked', 'Account Unlocked'), ('role_changed', 'Role Changed'), ('blacklist_added', 'IP Blacklisted'), ('blacklist_removed', 'IP Blacklist Removed'), ('quarantine_set', 'Account Quarantined'), ('quarantine_lifted', 'Quarantine Lifted'), ('member_anonymized', 'Member Anonymized'), ('other', 'Other')], max_length=30),
        ),
    ]
