# Generated by Django 5.2.17 on 2026-09-22 05:18
#
# 09-22-26 — Mason: pledges have to learn some of the fraternity's songs, so
# a new 'song' PledgeTask type can link directly to a Songbook entry. Both
# operations are additive/widening — safe on a live DB, no data to backfill.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0047_kaireport_identity_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgetask',
            name='song',
            field=models.ForeignKey(blank=True, help_text='For a Song-type task: the songbook entry pledges should learn. Shown to them on My Tasks with lyrics and the audio example.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledge_tasks', to='src.song'),
        ),
        migrations.AlterField(
            model_name='pledgetask',
            name='task_type',
            field=models.CharField(choices=[('task', 'Task'), ('quiz', 'Quiz'), ('milestone', 'Milestone'), ('reading', 'Reading'), ('song', 'Song')], default='task', max_length=20),
        ),
    ]
