# Generated by Django 5.1.7 on 2026-01-07 00:17

import src.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0048_committeevote_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=src.encrypted_fields.EncryptedCharField(help_text='Encrypted IP address of login attempt', max_length=180),
        ),
        migrations.AlterField(
            model_name='parliamentuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for password reset and notifications', max_length=254, null=True, unique=True),
        ),
    ]
