# Generated by Django 5.2.17 on 2026-09-23
#
# 09-23-26 — Mason: manual points adjustment on the education dashboard
# ("add, remove, or otherwise adjust... whether current or max"). Brand new
# table, no backfill — additive/safe on a live DB.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0048_pledgetask_song_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgePointAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_delta', models.SmallIntegerField(default=0, help_text='Change to points earned so far. Positive to add, negative to remove.')),
                ('max_delta', models.SmallIntegerField(default=0, help_text='Change to the max points currently possible. Positive to add, negative to remove.')),
                ('reason', models.CharField(blank=True, help_text='Optional note for why this adjustment was made — shown in the history log.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(limit_choices_to={'is_education_committee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='pledge_point_adjustments', to='src.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_point_adjustments', to=settings.AUTH_USER_MODEL)),
                ('pledge', models.ForeignKey(limit_choices_to={'member_type': 'Pledge'}, on_delete=django.db.models.deletion.CASCADE, related_name='point_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pledge Point Adjustment',
                'verbose_name_plural': 'Pledge Point Adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
