# Generated by Django 5.2.17 on 2026-09-24 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0049_pledgepointadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple')], default='yellow', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_notes_created', to=settings.AUTH_USER_MODEL)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_notes_done', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_notes_edited', to=settings.AUTH_USER_MODEL)),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='src.resolution')),
            ],
            options={
                'verbose_name': 'Resolution Note',
                'verbose_name_plural': 'Resolution Notes',
                'ordering': ['is_done', '-created_at'],
            },
        ),
    ]
