# Generated by Django 5.2.17 on 2026-09-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0050_resolutionnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolutionnote',
            name='anchor',
            field=models.CharField(blank=True, choices=[('header', 'Header'), ('preamble', 'Section I — Preamble'), ('resolved', 'Resolved clauses'), ('body', 'Section II — Body'), ('conclusion', 'Section III — Conclusion'), ('amendments', 'Tracked amendments')], default='', max_length=20),
        ),
    ]
