# Generated by Django 5.2.17 on 2026-09-25 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0051_resolutionnote_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='SectionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('was_active', models.BooleanField(default=True)),
                ('replaced_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('resolution', 'Resolution passed'), ('direct_edit', 'Direct edit in the C&B manager'), ('import', 'Document import'), ('backfill', 'Reconstructed from an earlier resolution')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_revisions', to='src.resolution')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='src.section')),
            ],
            options={
                'verbose_name': 'Section Revision',
                'verbose_name_plural': 'Section Revisions',
                'ordering': ['-replaced_at', '-pk'],
            },
        ),
    ]
