# Generated by Django 5.2.17 on 2026-09-25 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0053_backfill_section_revisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agendas', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas', to='src.event')),
                ('minutes', models.OneToOneField(blank=True, help_text='The minutes draft started from this agenda, once there is one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda', to='src.chapterminutes')),
            ],
            options={
                'verbose_name': 'Meeting Agenda',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('item_type', models.CharField(choices=[('call_to_order', 'Call to Order'), ('roll_call', 'Roll Call'), ('approve_minutes', 'Approval of Previous Minutes'), ('officer_reports', 'Officer Reports'), ('committee_reports', 'Committee Reports'), ('old_business', 'Old Business'), ('new_business', 'New Business'), ('announcements', 'Announcements'), ('adjournment', 'Adjournment'), ('custom', 'Other')], default='custom', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('presenter_text', models.CharField(blank=True, help_text='Typed name if not a member (e.g. a guest or advisor)', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('presenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='src.meetingagenda')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
