# Generated by Django 5.2.17 on 2026-10-01 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0055_fix_cnb_cross_references"),
    ]

    operations = [
        migrations.CreateModel(
            name="PledgeBigAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reveal_mode",
                    models.CharField(
                        choices=[
                            ("manual", "Manual — reveal when ready"),
                            ("timed", "Timed — reveal at a set time"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "reveals_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timed mode: when the pairing goes live on the site.",
                        null=True,
                    ),
                ),
                ("revealed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "big",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="big_assignments_as_big",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        limit_choices_to={"is_education_committee": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="big_assignments",
                        to="src.committee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_big_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pledge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="big_assignment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pledge Big Assignment",
                "verbose_name_plural": "Pledge Big Assignments",
                "ordering": ["pledge__name"],
                "indexes": [
                    models.Index(
                        fields=["reveal_mode", "revealed_at", "reveals_at"],
                        name="src_bigassign_due_idx",
                    )
                ],
            },
        ),
    ]
