# Generated by Django 5.2.17 on 2026-09-27 19:25

import src.models.landing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0055_fix_cnb_cross_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagecontent',
            name='contact_location',
            field=models.CharField(blank=True, default=src.models.landing.default_contact_location, max_length=200),
        ),
    ]
