# Generated by Django 5.2.17 on 2026-10-02 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_identifier_snapshots(apps, schema_editor):
    """
    Give every ALREADY-APPLIED amendment the identifier its section has today.

    From this release a passed resolution keeps citing the article/section
    numbers it was voted on with, even if a later resolution renumbers them.
    No renumbering has ever happened before this migration (there was no way
    to), so today's identifier IS the one each passed resolution used.
    """
    Amendment = apps.get_model('src', 'ResolutionAmendment')
    labels = {'foreword': 'Foreword', 'constitution': 'Constitution', 'bylaws': 'Bylaws', 'appendix': 'Appendix'}
    for amendment in (Amendment.objects.filter(applied=True, identifier_snapshot='')
                      .select_related('section__article__document')):
        section = amendment.section
        doc = labels.get(section.article.document.doc_type, section.article.document.doc_type)
        amendment.identifier_snapshot = f'{doc} Art. {section.article.number} § {section.number}'
        amendment.save(update_fields=['identifier_snapshot'])


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0056_pledge_big_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="resolutionamendment",
            name="identifier_snapshot",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name="ResolutionStructureChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("new_article", "New article"),
                            ("new_section", "New section"),
                            ("rename_article", "Rename an article"),
                            ("rename_section", "Rename a section"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="The new title.", max_length=200
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="new_section: the full text of the new section.",
                    ),
                ),
                ("old_title", models.CharField(blank=True, max_length=200)),
                ("applied", models.BooleanField(default=False)),
                ("result_label", models.CharField(blank=True, max_length=160)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="src.article",
                    ),
                ),
                (
                    "before_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="src.article",
                    ),
                ),
                (
                    "before_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="src.section",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="src.governingdocument",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="src.resolutionstructurechange",
                    ),
                ),
                (
                    "resolution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure_changes",
                        to="src.resolution",
                    ),
                ),
                (
                    "result_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="src.article",
                    ),
                ),
                (
                    "result_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="src.section",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="src.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resolution Structure Change",
                "ordering": ["added_at", "pk"],
            },
        ),
        migrations.RunPython(backfill_identifier_snapshots, migrations.RunPython.noop),
    ]
