# Generated by Django 5.2.17 on 2026-09-30 01:19

from django.db import migrations, models


def create_default_chapter(apps, schema_editor):
    """Multi-chapter 4a: this deployment's chapter, copied from settings.CHAPTER.

    Reads the live settings (not a frozen copy) on purpose: each deployment's
    row must match ITS OWN CHAPTER_* values. src.W007 catches later drift.
    """
    from django.conf import settings
    from django.utils.text import slugify
    Chapter = apps.get_model('src', 'Chapter')
    if Chapter.objects.exists():
        return
    cfg = dict(getattr(settings, 'CHAPTER', {}) or {})
    if not cfg.get('chapter_name') or not cfg.get('domain'):
        return  # nothing sensible to copy; W007 will say so
    Chapter.objects.create(slug=slugify(cfg['chapter_name'])[:50] or 'chapter', is_default=True, **cfg)


def remove_default_chapter(apps, schema_editor):
    apps.get_model('src', 'Chapter').objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ("src", "0056_landing_contact_location_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(help_text="e.g. 'alpha-mu'", unique=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The chapter this deployment serves. Exactly one row may have this (step 4a).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fraternity", models.CharField(max_length=100)),
                ("chapter_name", models.CharField(max_length=100)),
                ("school", models.CharField(max_length=150)),
                ("school_short", models.CharField(max_length=80)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("site_name", models.CharField(max_length=150)),
                ("domain", models.CharField(max_length=253, unique=True)),
                (
                    "crest",
                    models.CharField(
                        help_text="Static path to the crest image, e.g. images/crest.png",
                        max_length=200,
                    ),
                ),
                ("primary_color", models.CharField(max_length=20)),
                ("secondary_color", models.CharField(max_length=20)),
                ("motto", models.CharField(blank=True, max_length=200)),
                ("school_email_domain", models.CharField(blank=True, max_length=253)),
                ("founding_year", models.PositiveSmallIntegerField()),
                (
                    "founding_semester",
                    models.CharField(
                        choices=[("Fall", "Fall"), ("Spring", "Spring")], max_length=6
                    ),
                ),
                ("lettering_anchor", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "ordering": ["chapter_name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="chapter_single_default",
                    )
                ],
            },
        ),
        migrations.RunPython(create_default_chapter, remove_default_chapter),
    ]
