# Generated by Django 5.2.17 on 2026-10-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0057_resolution_structure_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="former_number",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name="section",
            name="removed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
