# Generated by Django 5.2.16 on 2026-10-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0056_pledge_big_assignment'),
        ('src', '0057_chapter'),
    ]

    operations = [
    ]
