# Generated by Django 5.2.18 on 2026-10-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0058_merge_0056_pledge_big_assignment_0057_chapter"),
        ("src", "0058_section_removed_by_resolution"),
    ]

    operations = []
